language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "bogalvan-github"
    token:
      secure: "413ebc2b5eac9bbadcbbecf11a701aa05b7159ca"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'